
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):

    def setupUi(self, Main):
        Main.setObjectName('Main')
        Main.resize(939, 649)
        Main.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Main.setStyleSheet('QPushButton {\nfont: 16pt "MS Shell Dlg 2";\nbackground-color: rgb(170, 255, 127);\nborder: 2px solid silver;\nborder-radius: 10px;\n}\nQPushButton:hover {\nbackground-color: rgb(106, 158, 78);\n}\nQPushButton:pressed {\nbackground-color: rgb(112, 112, 112);\n}\n\n\nQMenuBar:pressed {\nbackground-color: rgb(112, 112, 112);\n}\n\n\ncolor: rgb(109, 109, 109);')
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName('centralwidget')
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName('gridLayout')
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setMinimumSize(QtCore.QSize(457, 497))
        self.calendarWidget.setMouseTracking(False)
        self.calendarWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.calendarWidget.setObjectName('calendarWidget')
        self.gridLayout.addWidget(self.calendarWidget, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setToolTip('')
        self.pushButton.setWhatsThis('')
        self.pushButton.setStyleSheet('')
        self.pushButton.setObjectName('pushButton')
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setStyleSheet('color:rgb(0, 85, 255);\nfont: 16pt "MS Shell Dlg 2";\nbackground-color: rgb(170, 255, 127);\nselection-background-color: rgb(34, 34, 34);\nborder: 2px solid silver;\nborder-radius: 10px;\n')
        self.lineEdit.setText('')
        self.lineEdit.setObjectName('lineEdit')
        self.gridLayout.addWidget(self.lineEdit, 2, 0, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setStyleSheet('')
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName('pushButton_2')
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.timeEdit.setStyleSheet('font: 16pt "MS Shell Dlg 2";\nbackground-color: rgb(85, 255, 127);')
        self.timeEdit.setObjectName('timeEdit')
        self.gridLayout.addWidget(self.timeEdit, 3, 0, 1, 2)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(456, 497))
        self.textBrowser.setStyleSheet('background-color: rgb(170, 255, 127);\ncolor:rgb(0, 85, 255);\nfont: 11pt "MS Shell Dlg 2";\n')
        self.textBrowser.setObjectName('textBrowser')
        self.gridLayout.addWidget(self.textBrowser, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 939, 21))
        self.menubar.setObjectName('menubar')
        self.menu1 = QtWidgets.QMenu(self.menubar)
        self.menu1.setObjectName('menu')
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName('menu_2')
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName('menu_3')
        Main.setMenuBar(self.menubar)
        self.action_1 = QtWidgets.QAction(Main)
        self.action_1.setObjectName('action_1')
        self.action_2 = QtWidgets.QAction(Main)
        self.action_2.setObjectName('action_2')
        self.action_3 = QtWidgets.QAction(Main)
        self.action_3.setObjectName('action_3')
        self.action_4 = QtWidgets.QAction(Main)
        self.action_4.setObjectName('action_4')
        self.menu1.addAction(self.action_1)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menu_3.addAction(self.action_4)
        self.menubar.addAction(self.menu1.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)


    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate('Main', 'Планер'))
        self.pushButton.setText(_translate('Main', '+'))
        self.lineEdit.setPlaceholderText(_translate('Main', 'Введите задачу'))
        self.pushButton_2.setText(_translate('Main', '-'))
        self.menu1.setTitle(_translate('Main', 'Текст'))
        self.menu_2.setTitle(_translate('Main', 'Режимы'))
        self.menu_3.setTitle(_translate('Main', 'Настройки'))
        self.action_1.setText(_translate('Main', 'Сохранить'))
        self.action_2.setText(_translate('Main', 'Проекты'))
        self.action_3.setText(_translate('Main', 'Продукты'))
        self.action_4.setText(_translate('Main', 'Открыть'))


